package Bookings;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Cars.*;
import CustomerClients.ClientArraylist;
import CustomerClients.Clients;
import Interfaces.FrmInterface;
import Utils.UtilDate;
import Utils.UtilGui;
import exceptions.Bookings.BookingAlreadyStartedException;
import exceptions.Bookings.BookingNotFoundException;
import exceptions.Bookings.CarNotAvailableException;
import exceptions.Cars.CarRentedException;
import exceptions.Cars.DuplicateLicensePlateException;
import java.time.LocalDate;
import java.time.Year;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author unknown
 */
public class BookingFrm extends javax.swing.JFrame implements FrmInterface {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingFrm.class.getName());

    private BookingQueue list;
    private Booking booking;
    private ClientArraylist clientList;
    private CarHashMap carList; 

    
    
    /**
     * Creates new form CarFrm
     * @param clientList
     * @param carList
     * @param bookingList
     */
    public BookingFrm(ClientArraylist clientList, CarHashMap carList, BookingQueue bookingList) {
        initComponents();
//     if(clientList == null || carList == null || list == null) {
//        throw new IllegalArgumentException("Las listas no pueden estar vacias");
//    }    
        
        
    this.clientList = clientList;
    this.carList = carList;
    this.list = bookingList;  

    booking = null;

    
    //loadClients();
    //loadCars();
    showBookingStates();
    loadClientsAndCars();
    }
    

    private void showBookingStates() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (CarState carState: CarState.values()) {
            model.addElement(carState);
        }
        txtBookingState.setModel(model);
    }
    
    private void loadClientsAndCars() {
    DefaultComboBoxModel<Clients> clientModel = new DefaultComboBoxModel<>();
    for (Clients c : clientList.getList()) {
        clientModel.addElement(c);
    }
    txtClient.setModel((DefaultComboBoxModel) clientModel); // cast necesario

    DefaultComboBoxModel<Car> carModel = new DefaultComboBoxModel<>();
    for (Car car : carList.getAll()) {
        carModel.addElement(car);
    }
    txtCar.setModel((DefaultComboBoxModel) carModel); // cast necesario
}

    
    private void loadClients() {
    txtClient.removeAllItems();
    for (Clients c : clientList.getList()) {
        txtClient.addItem(c.getName());
    }
}

private void loadCars() {
    txtCar.removeAllItems();
    for (Car car : carList.getAll()) {
        txtCar.addItem(car.getBrand() + " " + car.getModel());
    }
}

    public void refresh() {
    loadClients();
    loadCars();
}

    
    private void showClients() {
    txtClient.removeAllItems();
    for (Clients c : clientList.getList()) {
        txtClient.addItem(c.getName());
    }
}

private void showCars() {
    txtCar.removeAllItems();
    for (Car car : carList.getAll()) {
        txtCar.addItem(car.getBrand() + " " + car.getModel());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelBtns = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelBody = new javax.swing.JPanel();
        JidBooking = new javax.swing.JLabel();
        jCar = new javax.swing.JLabel();
        jClients = new javax.swing.JLabel();
        jStartDate = new javax.swing.JLabel();
        jBookingState = new javax.swing.JLabel();
        jEndDate = new javax.swing.JLabel();
        txtIdBooking = new javax.swing.JFormattedTextField();
        txtEndDate = new javax.swing.JFormattedTextField();
        txtStartDate = new javax.swing.JFormattedTextField();
        txtBookingState = new javax.swing.JComboBox<>();
        txtCar = new javax.swing.JComboBox<>();
        txtClient = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(520, 400));

        jInternalFrame1.setVisible(true);

        jPanelTitle.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking Management");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanelBtns.setBackground(new java.awt.Color(51, 51, 51));

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageGUI/application_vnd.oasis.opendocument.spreadsheet (4).png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageGUI/3floppy_unmount (4).png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageGUI/updateIcon.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageGUI/deskbar-applet.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageGUI/application_exit (4).png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/crudsGui/button_ok (4).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtnsLayout = new javax.swing.GroupLayout(jPanelBtns);
        jPanelBtns.setLayout(jPanelBtnsLayout);
        jPanelBtnsLayout.setHorizontalGroup(
            jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );
        jPanelBtnsLayout.setVerticalGroup(
            jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtnsLayout.createSequentialGroup()
                .addGroup(jPanelBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelBody.setBackground(new java.awt.Color(102, 102, 102));

        JidBooking.setBackground(new java.awt.Color(255, 255, 255));
        JidBooking.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        JidBooking.setForeground(new java.awt.Color(255, 255, 255));
        JidBooking.setText("Id Booking");

        jCar.setBackground(new java.awt.Color(255, 255, 255));
        jCar.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jCar.setForeground(new java.awt.Color(255, 255, 255));
        jCar.setText("Car");

        jClients.setBackground(new java.awt.Color(255, 255, 255));
        jClients.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jClients.setForeground(new java.awt.Color(255, 255, 255));
        jClients.setText("Client");

        jStartDate.setBackground(new java.awt.Color(255, 255, 255));
        jStartDate.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jStartDate.setForeground(new java.awt.Color(255, 255, 255));
        jStartDate.setText("StartDate ");

        jBookingState.setBackground(new java.awt.Color(255, 255, 255));
        jBookingState.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jBookingState.setForeground(new java.awt.Color(255, 255, 255));
        jBookingState.setText("Booking State");

        jEndDate.setBackground(new java.awt.Color(255, 255, 255));
        jEndDate.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jEndDate.setForeground(new java.awt.Color(255, 255, 255));
        jEndDate.setText("EndDate");

        try {
            txtIdBooking.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtEndDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartDateActionPerformed(evt);
            }
        });

        txtBookingState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtCar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelBodyLayout = new javax.swing.GroupLayout(jPanelBody);
        jPanelBody.setLayout(jPanelBodyLayout);
        jPanelBodyLayout.setHorizontalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JidBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addComponent(jClients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStartDate)
                    .addComponent(jBookingState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtEndDate)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtBookingState, 0, 137, Short.MAX_VALUE)
                    .addComponent(txtClient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        jPanelBodyLayout.setVerticalGroup(
            jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JidBooking, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClients)
                    .addComponent(txtClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCar)
                    .addComponent(txtCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEndDate)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jStartDate)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBookingState)
                    .addComponent(txtBookingState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBody, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDesktopPane2.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 571, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStartDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        ClientArraylist clientList = new ClientArraylist(); // 👈 instancia real
        CarHashMap carList = new CarHashMap();              // 👈 instancia real
        BookingQueue bookingQueue = new BookingQueue();
        new BookingFrm(clientList, carList,bookingQueue).setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JidBooking;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jBookingState;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCar;
    private javax.swing.JLabel jClients;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jEndDate;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBody;
    private javax.swing.JPanel jPanelBtns;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JComboBox<String> txtBookingState;
    private javax.swing.JComboBox<String> txtCar;
    private javax.swing.JComboBox<String> txtClient;
    private javax.swing.JFormattedTextField txtEndDate;
    private javax.swing.JFormattedTextField txtIdBooking;
    private javax.swing.JFormattedTextField txtStartDate;
    // End of variables declaration//GEN-END:variables

    

    @Override
    public void clear() {
    txtIdBooking.setText("");
    txtClient.setSelectedIndex(-1); 
    txtCar.setSelectedIndex(-1);  
    txtStartDate.setText("");
    txtEndDate.setText("");
    txtBookingState.setSelectedIndex(-1);
    }

    @Override
    public boolean validateRequiere() {
    return UtilGui.validateRequiere(txtIdBooking,txtClient,txtCar,txtEndDate,txtBookingState);
    }

   @Override
public void save() {
    try {
        String idBooking = txtIdBooking.getText();

        // Recuperar directamente los objetos seleccionados
        Clients selectedClient = (Clients) txtClient.getSelectedItem();
        Car selectedCar = (Car) txtCar.getSelectedItem();

        // Validaciones
        if (selectedClient == null) {
            JOptionPane.showMessageDialog(this, "Client not found");
            return;
        }

        if (selectedCar == null) {
            JOptionPane.showMessageDialog(this, "Car not found");
            return;
        }

        LocalDate startDate = UtilDate.toLocalDate(txtStartDate.getText());
        LocalDate endDate = UtilDate.toLocalDate(txtEndDate.getText());
        BookingState bookingState = (BookingState) txtBookingState.getSelectedItem();

        // Crear la reserva
        booking = new Booking(idBooking, selectedClient, selectedCar, startDate, endDate, bookingState);

        if (!list.correctAdd(booking)) {
            JOptionPane.showMessageDialog(this, "The record was not added");
            return;
        }

        UtilGui.showMessage(this, "Register added " + selectedCar.getLicensePlate(), "Agregado");
        showBookingStates();

    } catch (CarNotAvailableException ex) {
        System.getLogger(BookingFrm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
}



   @Override
public void update() {
    if (booking == null) {
        UtilGui.showErrorMessage(this, "No record has been selected", "Error");
        return;
    }

    if (!validateRequiere()) {
        UtilGui.showErrorMessage(this, "Required data is missing", "Error");
        return;
    }

    try {
        // Nuevo estado de la reserva
        BookingState bookingState = (BookingState) txtBookingState.getSelectedItem();
        booking.setBookingState(bookingState);

        // Nuevo vehículo
        String carPlate = (String) txtCar.getSelectedItem();

        Car newCar = carList.find(carPlate);

        if (newCar == null) {
            UtilGui.showErrorMessage(this, "Car not found: " + carPlate, "Error");
            return;
        }

        if (newCar.getCarState() == CarState.RENTED) {
            UtilGui.showErrorMessage(this, "This car is already rented", "Error");
            return;
        }

        // Liberar carro anterior
        Car oldCar = booking.getCar();
        if (oldCar != null) {
            oldCar.setCarState(CarState.AVAILABLE);
        }

        // Asignar nuevo carro y marcarlo como RENTED
        newCar.setCarState(CarState.RENTED);
        booking.setCar(newCar);

        UtilGui.showMessage(this, "Booking updated successfully", "Update");

    } catch (Exception e) {
         JOptionPane.showMessageDialog(null, 
        "Generic Error: " + e.getMessage(), 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
    }
}

    @Override
    public void delete() {
          try {
        if (booking == null) {
            UtilGui.showErrorMessage(this, "No record selected", "Error");
            return;
        }

        int option = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to remove this record?",
            "Confirm elimination",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (option != JOptionPane.YES_OPTION) {
            return;
        }

        if (!list.correctRemove(booking)) {
            JOptionPane.showMessageDialog(this, "Record not removed");
            return;
        }

        
        Car car = booking.getCar();
        if (car != null) {
            car.setCarState(CarState.AVAILABLE);
        }

        booking = null;
        clear();

    }   catch (BookingNotFoundException e) {
         JOptionPane.showMessageDialog(null, 
        "No booking found: " + e.getMessage(), 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
    } catch (BookingAlreadyStartedException e) {
         JOptionPane.showMessageDialog(null, 
        "Booking Already Started Error: " + e.getMessage(), 
        "Error", 
        JOptionPane.ERROR_MESSAGE);
    }
    }

    @Override
    public void search() {
        BookingCrud crud = new BookingCrud(this,true); 
    crud.setList(list);
   crud.setVisible(true);
   booking=crud.getBooking();
   
   if(booking==null){
       clear();
   }else{
       showData();
   }
    }

   @Override
public void showData() {
    if (booking == null) {
        clear();
        return;
    }

    txtIdBooking.setText(booking.getIdBooking());
    txtClient.setSelectedItem(booking.getClient());
    txtCar.setSelectedItem(booking.getCar());
    txtStartDate.setText(booking.getStartDate().toString());
    txtEndDate.setText(booking.getEndDate().toString());
    txtBookingState.setSelectedItem(booking.getBookingState());
}


   
}
